export const types = Object.freeze({
    SET_EXCHANGE_RATES: 'SET_EXCHANGE_RATES',
    SET_CURRENCY_CONVERSIONS: 'SET_CURRENCY_CONVERSIONS',
    SET_CURRENCY_STATISTICS_EUR: 'SET_CURRENCY_STATISTICS_EUR',
    SET_CURRENCY_STATISTICS_USD: 'SET_CURRENCY_STATISTICS_USD',
});