version: "3.3"
services:
    postgres:
        image: postgres
        restart: always
        container_name: "mg_dev_postgres"
        environment:
            POSTGRES_DB: "dev_db"
            POSTGRES_USER: "dev_user"
            POSTGRES_PASSWORD: "dev_postgres"
        ports:
            - "15432:5432"
