version: "3.3"
services:
    postgres:
        image: postgres
        restart: always
        container_name: "mg_dev_postgres"
        environment:
            POSTGRES_DB: "dev_db"
            POSTGRES_USER: "dev_user"
            POSTGRES_PASSWORD: "dev_postgres"
        ports:
            - "15432:5432"
        volumes:
            - ../.infrastructure/mg_website_postgres:/var/lib/postgresql/data
    prometheus:
        image: prom/prometheus:latest
        restart: always
        container_name: "mg_dev_prometheus"
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana-oss:latest
        restart: always
        container_name: "mg_dev_grafana"
        ports:
            - "3000:3000"

