version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_container
    ports:
      - "14000:9042"
    environment:
      - CASSANDRA_KEYSPACE=my_keyspace
      - CASSANDRA_REPLICATION_FACTOR=1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:


