export const types = Object.freeze({
    SET_ACTIVE_PROFILE: 'SET_ACTIVE_PROFILE',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    REMOVE_ACTIVE_PROFILE: 'REMOVE_ACTIVE_PROFILE',
    REMOVE_AUTH_TOKEN: 'REMOVE_AUTH_TOKEN',
});