version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    container_name: "mg_prod_postgres"
    environment:
      POSTGRES_DB: "dev_db"
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_postgres"
    ports:
      - "15432:5432"
    volumes:
      - ../.infrastructure/mg_website_postgres:/var/lib/postgresql/data
    networks:
      - mg_net
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: "mg_prod_prometheus"
    ports:
      - "19090:9090"
    networks:
      - mg_net
  backend:
    image: mgelios/mg_website_main_backend:latest
    restart: always
    container_name: "mg_prod_main_backend"
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      - mg_net
  frontend:
    image: mgelios/mg_website_main_frontend:latest
    restart: always
    container_name: "mg_prod_main_frontend"
    ports:
      - "80:80"
    networks:
      - mg_net
networks:
  mg_net:
    driver: bridge