spring:
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/main-liquibase-changelog.xml"
  datasource:
    url: "jdbc:postgresql://localhost:5432/dev_db"
    username: "dev_user"
    password: "dev_postgres"
    platform: "postgres"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        jdbc:
          lob:
            non_contextual_creation: true
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-doc"
server:
  port: 8080
  error:
    whitelabel:
      enabled: false